apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: xrpl
  name: xrpl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: xrpl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: xrpl
    spec:
      containers:
      - image: public.ecr.aws/p9t2a4b9/xrpl:latest
        name: webapp
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 51235
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: xrpl
  labels:
    run: xrpl
spec:
  ports:
  - port: 51235
    protocol: TCP
  selector:
    app: xrpl
  type: LoadBalancer
